### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by Rehana1972** [Rehana1972/Prework-study-guide#3]
# JavaScript

## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I can see the four topics I learned listed along with a suggestion on what I should study first

**Comment by ninyox** [comment]
To create a Prework Study Guide webpage for boot camp students, you can follow these steps:

1. HTML Structure:
   - Create an HTML file (e.g., `index.html`).
   - Set up the basic structure of the HTML document, including `<html>`, `<head>`, and `<body>` tags.

2. Head Section:
   - Inside the `<head>` tag, add a `<title>` element to set the title of the webpage.
   - Link a CSS file to style the webpage by adding a `<link>` tag with the `rel` attribute set to "stylesheet" and the `href` attribute pointing to your CSS file.

3. Body Section:
   - Within the `<body>` tag, create a heading element (e.g., `<h1>`) to display the title of the study guide (e.g., "Prework Study Guide").
   - Below the heading, create an unordered list (e.g., `<ul>`) to list the four topics learned in the boot camp.

4. List the Topics:
   - Inside the `<ul>`, create four list items (e.g., `<li>`) to represent each topic.
   - Include the name of each topic as the content of the list item.

5. Suggestion on What to Study First:
   - After the list of topics, add a paragraph (e.g., `<p>`) that provides a suggestion on what students should study first.
   - Write a sentence or two to guide students on which topic to start with.

6. CSS Styling:
   - Create a CSS file (e.g., `styles.css`) and link it to your HTML file.
   - Define styles for the elements in your webpage to make it visually appealing and easy to read.
   - You can use CSS properties like font-size, color, margin, padding, etc., to customize the appearance of your webpage.

7. Test and Refine:
   - Open your HTML file in a web browser to test the layout and appearance.
   - Make any necessary adjustments to the HTML or CSS to improve the presentation and readability.

Here's an example of how the HTML structure might look:

```
<!DOCTYPE html>
<html>
<head>
  <title>Prework Study Guide</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <h1>Prework Study Guide</h1>
  <ul>
    <li>Topic 1</li>
    <li>Topic 2</li>
    <li>Topic 3</li>
    <li>Topic 4</li>
  </ul>
  <p>Start by studying Topic 1 to build a strong foundation.</p>
</body>
</html>
```

Remember to customize the content, styling, and file names according to your preferences. Update the CSS file (`styles.css`) to define the desired styles for your webpage.
